### ISSUE TITLE
Users should be able to personalize Ctype label

### ISSUE THREAD

**Issue by jpmarindiaz** [datasketch/hotr#13]
Users may want to edit the names of the column types, example.
Cat -> Categorías
Num -> Números
Useful for multilingual apps

**Comment by ddazal** [comment]
@jpmarindiaz Users or developers?

**Comment by jpmarindiaz** [comment]
Developers

**Comment by ddazal** [comment]
Done here 87fe02862ef092d662e47df43d15dd95c14fd685
