### ISSUE TITLE
filter options in header

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/hotr#2]
![imagen](https://user-images.githubusercontent.com/17035597/73709859-41d76b00-46d0-11ea-97cb-4a815870a36d.png)

**Comment by wfjvdham** [comment]
Adding (like shown [here](https://handsontable.com/docs/5.0.1/demo-dropdown-menu.html))
```javascript
dropdownMenu: true,
filters: true,
```
Does not work, I cannot figure out why...

**Comment by ddazal** [comment]
Did you notice the _PRO_ badge on the docs, @wfjvdham ? I don't know if we're using the PRO version :hushed:

**Comment by wfjvdham** [comment]
Good point! I don't think so...
