### ISSUE TITLE
hotr function trims columns

### ISSUE THREAD

**Issue by lenafm** [datasketch/hotr#39]
When used as follows, the data in `input$data_input` seems to be trimmed at 26 columns even if `inputData()` has more columns. 

```hotr("data_input", data = inputData(), options = list(height = 200))```

**Comment by jpmarindiaz** [comment]
I thought no one would notice ;)

@ddazal can you please expand this so we can use `aa, ab ..., zz`  after `z` for column names? 
https://github.com/datasketch/hotr/blob/master/inst/lib/hotr/hotrHelpers.js#L109

**Comment by ddazal** [comment]
Done 77d713309a612e572419494d5a96679fbe61646c
