### ISSUE TITLE
width and height dshot

### ISSUE THREAD

**Issue by CamilaAchuri** [datasketch/hotr#5]
the table size is nonfunctional in shinypanel

**Comment by CamilaAchuri** [comment]
![imagen](https://user-images.githubusercontent.com/17035597/73712216-5ff49980-46d7-11ea-8b01-c4a282b9979d.png)

**Comment by wfjvdham** [comment]
How can I reproduce this? I also need the shinypanel package?

**Comment by ddazal** [comment]
Fixed in 6655aa63e299a40c6711e1ed1899cf051df9d127
